### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by tofi86**
Add german translation files.

Yes/No buttons in Dialogs are still in French though, see https://github.com/edrlab/readium-desktop/issues/128#issuecomment-377915633

### CODE REVIEW

**Comment by tofi86** [comment]
Dear maintainers: Please ping me a couple of days before the next public release / every public release after its feature-freeze so I can update the german language file in time!

**Comment by llemeurfr** [comment]
Thanks a lot Tobias, for these translations. 
Note: I see that a TravisCI lint check has failed... 
Ok, we'll ping you (as much as we can trigger our memory). 
Don't hesitate to give us info about your use of Readium Desktop.

**Comment by tofi86** [comment]
@llemeurfr yeah, just noted a linting error. Will fix it.

**Comment by danielweck** [comment]
Hello Tobias, I believe Pull Requests must target the 'develop' branch, not 'master' (which is used to tag releases).

**Comment by tofi86** [comment]
Hi Daniel, alright, I changed target to `develop`. Travis running again, but shouldn't be a problem as `master` and `devlop` seem to be even. Will do that for the other PR's as well.

You could add a GitHub Contributing file to state this info.

**Comment by JayPanoz** [comment]
> You could add a GitHub Contributing file to state this info.

See also [PR templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) e.g. [the one for readium-css](https://github.com/readium/readium-css/blob/develop/.github/pull_request_template.md), with a checklist at the very beginning to make sure everything is OK. Not perfect but it’s at least another safety net.

**Comment by tofi86** [comment]
Thanks for merging!

**Pull request merged**
